[package]
name = "punchafriend"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.96"
bevy = "0.15"
bevy_egui = {version = "0.33.0", features = ["serde"]}
bevy_rapier2d = {version = "0.29.0", features = ["parallel", "serde-serialize", "simd-stable", "debug-render-2d"]}
tokio = {version = "1.43.0", features = ["full"]}
mlua = {version = "0.10.3", features = ["luajit", "vendored", "send"]}

# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3
